/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class Calc_Cientifica extends javax.swing.JFrame {

    /**
     * Creates new form Calc
     */
    private String entrada="";
    private double numero1, numero2;             
    private String operador;
    private String historial= "";
    public Calc_Cientifica() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Calculadora Cientifica - Luis Pedro Priego");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton17 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jtxtCantidad = new javax.swing.JTextField();
        jbnt7 = new javax.swing.JButton();
        jbnt8 = new javax.swing.JButton();
        jbnt9 = new javax.swing.JButton();
        jbntraiz = new javax.swing.JButton();
        jbnt0 = new javax.swing.JButton();
        jbnt1 = new javax.swing.JButton();
        jbnt2 = new javax.swing.JButton();
        jbnt4 = new javax.swing.JButton();
        jbnt5 = new javax.swing.JButton();
        jbntresta = new javax.swing.JButton();
        jbntsuma = new javax.swing.JButton();
        jbnt6 = new javax.swing.JButton();
        jbnt3 = new javax.swing.JButton();
        jbntdecimal = new javax.swing.JButton();
        jbntX = new javax.swing.JButton();
        jbntdiv = new javax.swing.JButton();
        jbntporcentaje = new javax.swing.JButton();
        jbntborrador = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jbntigual = new javax.swing.JButton();

        jButton17.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        jButton17.setText("6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jtxtCantidad.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jtxtCantidad.setEnabled(false);

        jbnt7.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbnt7.setText("7");
        jbnt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnt7ActionPerformed(evt);
            }
        });

        jbnt8.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbnt8.setText("8");
        jbnt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnt8ActionPerformed(evt);
            }
        });

        jbnt9.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbnt9.setText("9");
        jbnt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnt9ActionPerformed(evt);
            }
        });

        jbntraiz.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbntraiz.setText("√");
        jbntraiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntraizActionPerformed(evt);
            }
        });

        jbnt0.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbnt0.setText("0");
        jbnt0.setToolTipText("");
        jbnt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnt0ActionPerformed(evt);
            }
        });

        jbnt1.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbnt1.setText("1");
        jbnt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnt1ActionPerformed(evt);
            }
        });

        jbnt2.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbnt2.setText("2");
        jbnt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnt2ActionPerformed(evt);
            }
        });

        jbnt4.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbnt4.setText("4");
        jbnt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnt4ActionPerformed(evt);
            }
        });

        jbnt5.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbnt5.setText("5");
        jbnt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnt5ActionPerformed(evt);
            }
        });

        jbntresta.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbntresta.setText("-");
        jbntresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntrestaActionPerformed(evt);
            }
        });

        jbntsuma.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbntsuma.setText("+");
        jbntsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntsumaActionPerformed(evt);
            }
        });

        jbnt6.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbnt6.setText("6");
        jbnt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnt6ActionPerformed(evt);
            }
        });

        jbnt3.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbnt3.setText("3");
        jbnt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnt3ActionPerformed(evt);
            }
        });

        jbntdecimal.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbntdecimal.setText(".");
        jbntdecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntdecimalActionPerformed(evt);
            }
        });

        jbntX.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbntX.setText("X");
        jbntX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntXActionPerformed(evt);
            }
        });

        jbntdiv.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbntdiv.setText("/");
        jbntdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntdivActionPerformed(evt);
            }
        });

        jbntporcentaje.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbntporcentaje.setText("%");
        jbntporcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntporcentajeActionPerformed(evt);
            }
        });

        jbntborrador.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbntborrador.setText("CE");
        jbntborrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntborradorActionPerformed(evt);
            }
        });

        jButton20.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jButton20.setText("C");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jbntigual.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jbntigual.setText("=");
        jbntigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntigualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbnt4, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(jbnt5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jbnt6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jbntX, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbntraiz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(jbntporcentaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9)
                        .addComponent(jbntborrador)
                        .addGap(9, 9, 9)
                        .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbnt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(jbnt2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jbnt3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jbntresta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jtxtCantidad)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbntdecimal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(jbnt0, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jbntigual, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jbntsuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbnt7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6)
                        .addComponent(jbnt8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(8, 8, 8)
                        .addComponent(jbnt9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(jbntdiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(102, 102, 102))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbntraiz)
                    .addComponent(jbntporcentaje)
                    .addComponent(jbntborrador)
                    .addComponent(jButton20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnt7)
                    .addComponent(jbnt8)
                    .addComponent(jbnt9)
                    .addComponent(jbntdiv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnt4)
                    .addComponent(jbnt5)
                    .addComponent(jbnt6)
                    .addComponent(jbntX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnt1)
                    .addComponent(jbnt2)
                    .addComponent(jbnt3)
                    .addComponent(jbntresta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbntdecimal)
                    .addComponent(jbnt0)
                    .addComponent(jbntsuma)
                    .addComponent(jbntigual))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbntigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntigualActionPerformed
 
    double resultado = 0;

    if (!operador.equals("√") && !operador.equals("%")) {
        numero2 = Double.parseDouble(entrada);
    }

    if (operador.equals("+")) {
        resultado = numero1 + numero2;
    }
    else if (operador.equals("-")) {
        resultado = numero1 - numero2;
    }
    else if (operador.equals("X")) {
        resultado = numero1 * numero2;
    }
    else if (operador.equals("/")) {
        if (numero2 != 0) {
            resultado = numero1 / numero2;
        } else {
            jtxtCantidad.setText("Error");
            return;
        }
    }

    entrada = String.valueOf(resultado);
    jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbntigualActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        entrada="";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jbntborradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntborradorActionPerformed

    historial = "";
    entrada = "";
    jtxtCantidad.setText("");
    }//GEN-LAST:event_jbntborradorActionPerformed

    private void jbntporcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntporcentajeActionPerformed
        //Capturar y converir el valor o texto a un valor
        //Limpiar la caja de texto
        //Capturar el signo
        //Envio en pantallalo que he capturado
        if (!entrada.equals("")) {
        numero1 = Double.parseDouble(entrada);
        double resultado = numero1 / 100;

        entrada = String.valueOf(resultado);
        jtxtCantidad.setText(entrada);
    }
    }//GEN-LAST:event_jbntporcentajeActionPerformed

    private void jbntdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntdivActionPerformed
        //Capturar y converir el valor o texto a un valor
        //Limpiar la caja de texto
        //Capturar el signo
        //Envio en pantallalo que he capturado       
        numero1=Double.parseDouble(entrada);
        entrada="";
        operador="/";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbntdivActionPerformed

    private void jbntXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntXActionPerformed
        //Capturar y converir el valor o texto a un valor
        //Limpiar la caja de texto
        //Capturar el signo
        //Envio en pantallalo que he capturado       
        numero1=Double.parseDouble(entrada);
        entrada="";
        operador="X";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbntXActionPerformed

    private void jbntdecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntdecimalActionPerformed
    if (!entrada.contains(".")) {
        if (entrada.equals("")) {
            entrada = "0.";
        } else {
            entrada = entrada + ".";
        }
        jtxtCantidad.setText(entrada);
    }
    }//GEN-LAST:event_jbntdecimalActionPerformed

    private void jbnt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnt3ActionPerformed
        // Llamar y capturar un dato....
        //Imprimir
        entrada = entrada  + 3;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbnt3ActionPerformed

    private void jbnt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnt6ActionPerformed
        // Llamar y capturar un dato....
        //Imprimir
        entrada = entrada  + 6;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbnt6ActionPerformed

    private void jbntsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntsumaActionPerformed
        //Capturar y converir el valor o texto a un valor
        //Limpiar la caja de texto
        //Capturar el signo
        //Envio en pantallalo que he capturado       
        numero1=Double.parseDouble(entrada);
        entrada="";
        operador="+";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbntsumaActionPerformed

    private void jbntrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntrestaActionPerformed
        //Capturar y converir el valor o texto a un valor
        //Limpiar la caja de texto
        //Capturar el signo
        //Envio en pantallalo que he capturado
        numero1=Double.parseDouble(entrada);
        entrada="";
        operador="-";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbntrestaActionPerformed

    private void jbnt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnt5ActionPerformed
        // Llamar y capturar un dato....
        //Imprimir
        entrada = entrada  + 5;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbnt5ActionPerformed

    private void jbnt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnt4ActionPerformed
        // Llamar y capturar un dato....
        //Imprimir
        entrada = entrada  + 4;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbnt4ActionPerformed

    private void jbnt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnt2ActionPerformed
        // Llamar y capturar un dato....
        //Imprimir
        entrada = entrada  + 2;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbnt2ActionPerformed

    private void jbnt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnt1ActionPerformed
        // Llamar y capturar un dato....
        //Imprimir
        entrada = entrada  + 1;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbnt1ActionPerformed

    private void jbnt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnt0ActionPerformed
        // Llamar y capturar un dato....
        //Imprimir
        entrada = entrada  + 0;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbnt0ActionPerformed

    private void jbntraizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntraizActionPerformed
        //Capturar y converir el valor o texto a un valor
        //Limpiar la caja de texto
        //Capturar el signo
        //Envio en pantallalo que he capturado
    if (!entrada.equals("")) {
        numero1 = Double.parseDouble(entrada);

        if (numero1 >= 0) {
            double resultado = Math.sqrt(numero1);
            entrada = String.valueOf(resultado);
            jtxtCantidad.setText(entrada);
        } else {
            jtxtCantidad.setText("Error");
        }
    }

    }//GEN-LAST:event_jbntraizActionPerformed

    private void jbnt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnt9ActionPerformed
        // Llamar y capturar un dato....
        //Imprimir
        entrada = entrada  + 9;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbnt9ActionPerformed

    private void jbnt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnt8ActionPerformed
        // Llamar y capturar un dato....
        //Imprimir
        entrada = entrada  + 8;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbnt8ActionPerformed

    private void jbnt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnt7ActionPerformed
        // Llamar y capturar un dato....
        //Imprimir
        entrada = entrada  + 7;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbnt7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc_Cientifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc_Cientifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc_Cientifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc_Cientifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc_Cientifica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbnt0;
    private javax.swing.JButton jbnt1;
    private javax.swing.JButton jbnt2;
    private javax.swing.JButton jbnt3;
    private javax.swing.JButton jbnt4;
    private javax.swing.JButton jbnt5;
    private javax.swing.JButton jbnt6;
    private javax.swing.JButton jbnt7;
    private javax.swing.JButton jbnt8;
    private javax.swing.JButton jbnt9;
    private javax.swing.JButton jbntX;
    private javax.swing.JButton jbntborrador;
    private javax.swing.JButton jbntdecimal;
    private javax.swing.JButton jbntdiv;
    private javax.swing.JButton jbntigual;
    private javax.swing.JButton jbntporcentaje;
    private javax.swing.JButton jbntraiz;
    private javax.swing.JButton jbntresta;
    private javax.swing.JButton jbntsuma;
    private javax.swing.JTextField jtxtCantidad;
    // End of variables declaration//GEN-END:variables
}
