/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculadorabasica.luispriego;

/**
 *
 * @author LABORATORIO
 */
public class jfrmCalc extends javax.swing.JFrame {
    

    /**
     * Variables publicas, privadas, generales, globales y genericas
     */
    private String entrada="";
    private int numero1, numero2;             
    private String operador;
    public jfrmCalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jbtnMulti1 = new javax.swing.JButton();
        jtxtCantidad = new javax.swing.JTextField();
        jbtn8 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn9 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtnborrar = new javax.swing.JButton();
        jbtnsuma = new javax.swing.JButton();
        jbtnresta = new javax.swing.JButton();
        jbtnigual = new javax.swing.JButton();
        jbtnMulti = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jbtnDiv = new javax.swing.JButton();

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jButton8.setText("4");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");

        jbtnMulti1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jbtnMulti1.setText("X");
        jbtnMulti1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMulti1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtxtCantidad.setEnabled(false);

        jbtn8.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jbtn8.setForeground(new java.awt.Color(51, 51, 255));
        jbtn8.setText("8");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtn7.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jbtn7.setForeground(new java.awt.Color(51, 51, 255));
        jbtn7.setText("7");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });

        jbtn6.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jbtn6.setForeground(new java.awt.Color(51, 51, 255));
        jbtn6.setText("6");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtn9.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jbtn9.setForeground(new java.awt.Color(51, 51, 255));
        jbtn9.setText("9");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtn5.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jbtn5.setForeground(new java.awt.Color(51, 51, 255));
        jbtn5.setText("5");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtn4.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jbtn4.setForeground(new java.awt.Color(51, 51, 255));
        jbtn4.setText("4");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtn2.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jbtn2.setForeground(new java.awt.Color(51, 51, 255));
        jbtn2.setText("2");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtn1.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jbtn1.setForeground(new java.awt.Color(51, 51, 255));
        jbtn1.setText("1");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtn3.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jbtn3.setForeground(new java.awt.Color(51, 51, 255));
        jbtn3.setText("3");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtnborrar.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jbtnborrar.setForeground(new java.awt.Color(51, 51, 255));
        jbtnborrar.setText("AC");
        jbtnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnborrarActionPerformed(evt);
            }
        });

        jbtnsuma.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jbtnsuma.setForeground(new java.awt.Color(51, 51, 255));
        jbtnsuma.setText("+");
        jbtnsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsumaActionPerformed(evt);
            }
        });

        jbtnresta.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jbtnresta.setForeground(new java.awt.Color(51, 51, 255));
        jbtnresta.setText("-");
        jbtnresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnrestaActionPerformed(evt);
            }
        });

        jbtnigual.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jbtnigual.setForeground(new java.awt.Color(51, 51, 255));
        jbtnigual.setText("=");
        jbtnigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnigualActionPerformed(evt);
            }
        });

        jbtnMulti.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jbtnMulti.setForeground(new java.awt.Color(51, 51, 255));
        jbtnMulti.setText("X");
        jbtnMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMultiActionPerformed(evt);
            }
        });

        jbtn0.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jbtn0.setForeground(new java.awt.Color(51, 51, 255));
        jbtn0.setText("0");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });

        jbtnDiv.setFont(new java.awt.Font("Tempus Sans ITC", 2, 24)); // NOI18N
        jbtnDiv.setForeground(new java.awt.Color(51, 51, 255));
        jbtnDiv.setText("/");
        jbtnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn1)
                                .addGap(6, 6, 6)
                                .addComponent(jbtn2)
                                .addGap(6, 6, 6)
                                .addComponent(jbtn3)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnresta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn7)
                                .addGap(6, 6, 6)
                                .addComponent(jbtn8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn9)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnborrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnMulti)
                                .addGap(6, 6, 6)
                                .addComponent(jbtnDiv)
                                .addGap(6, 6, 6)
                                .addComponent(jbtn0)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnigual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn4)
                                .addGap(6, 6, 6)
                                .addComponent(jbtn5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtn6)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnsuma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(112, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jtxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn8)
                    .addComponent(jbtn7)
                    .addComponent(jbtn9)
                    .addComponent(jbtnborrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn4)
                    .addComponent(jbtn6)
                    .addComponent(jbtn5)
                    .addComponent(jbtnsuma))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn3)
                    .addComponent(jbtn2)
                    .addComponent(jbtn1)
                    .addComponent(jbtnresta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnMulti)
                    .addComponent(jbtnDiv)
                    .addComponent(jbtn0)
                    .addComponent(jbtnigual))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        // TODO add your handling code here:
        entrada = entrada  + 8;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        // Llamar y capturar un dato....
        //Imprimir
        entrada = entrada  + 7;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        // TODO add your handling code here:
        entrada = entrada  + 6;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        // TODO add your handling code here:
        entrada = entrada  + 9;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        // TODO add your handling code here:
        entrada = entrada  + 5;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        // TODO add your handling code here:
        entrada = entrada  + 4;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        // TODO add your handling code here:
        entrada = entrada  + 2;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        // TODO add your handling code here:
        entrada = entrada  + 1;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        // TODO add your handling code here:
        entrada = entrada  + 3;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtnMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMultiActionPerformed
        // TODO add your handling code here:
        numero1=Integer.parseInt(entrada);
        entrada="";
        operador="X";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnMultiActionPerformed

    private void jbtnMulti1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMulti1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnMulti1ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        // TODO add your handling code here:
        entrada = entrada  + 0;
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDivActionPerformed
        // TODO add your handling code here:
        numero1=Integer.parseInt(entrada);
        entrada="";
        operador="/";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnDivActionPerformed

    private void jbtnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsumaActionPerformed
        //Capturar y converir el valor o texto a un valor
        //Limpiar la caja de texto
        //Capturar el signo
        //Envio en pantallalo que he capturado
        numero1=Integer.parseInt(entrada);
        entrada="";
        operador="+";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnsumaActionPerformed

    private void jbtnrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnrestaActionPerformed
        // TODO add your handling code here:
        numero1=Integer.parseInt(entrada);
        entrada="";
        operador="-";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnrestaActionPerformed

    private void jbtnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnborrarActionPerformed
        // TODO add your handling code here:
        entrada="0";
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnborrarActionPerformed

    private void jbtnigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnigualActionPerformed
        // Capturar numero 2
        numero2 = Integer.parseInt(entrada);
        jtxtCantidad.setText("");
        entrada = "";
        
        double resultado = 0; 

        if (operador.equals("+")) {
            resultado = (double) numero1 + numero2;
        } 
        else if (operador.equals("-")) {
            resultado = (double) numero1 - numero2;
        } 
        else if (operador.equals("X")) {
            resultado = (double) numero1 * numero2;
        } 
        else if (operador.equals("/")) {
            if (numero2 != 0) {
                resultado = (double) numero1 / numero2;
            } else {
                jtxtCantidad.setText("Error");
                return;
            }
        }

        entrada = String.valueOf(resultado);
        jtxtCantidad.setText(entrada);
    }//GEN-LAST:event_jbtnigualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnDiv;
    private javax.swing.JButton jbtnMulti;
    private javax.swing.JButton jbtnMulti1;
    private javax.swing.JButton jbtnborrar;
    private javax.swing.JButton jbtnigual;
    private javax.swing.JButton jbtnresta;
    private javax.swing.JButton jbtnsuma;
    private javax.swing.JTextField jtxtCantidad;
    // End of variables declaration//GEN-END:variables
}
